apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

images:
- name: goapp
  newName: wesleywillians/argocd
  newTag: 0ae6d7ed49cf4f1ce4e0b426fa2b71f3d2dc6b4b
