apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml

namespace: default

images:
- name: goapp
  newName: wesleywillians/argocd
  newTag: 7e57b32a1e3685c82dba798991b8c2618eabf3aa
